# Generated by Django 4.2.24 on 2025-09-25 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payer_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments_app.client', verbose_name='Плательщик'),
            preserve_default=False,
        ),
    ]
